/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiTranslateBlogRouteImport } from './routes/api.translate-blog'
import { Route as ApiTagsRouteImport } from './routes/api/tags'
import { Route as ApiDebugTranslationsRouteImport } from './routes/api/debug-translations'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiBlogsRouteImport } from './routes/api/blogs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCalculatorSettingsRouteImport } from './routes/admin.calculator-settings'
import { Route as AdminCalculatorQuotesRouteImport } from './routes/admin.calculator-quotes'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as ApiBlogsSlugRouteImport } from './routes/api/blogs.$slug'
import { Route as AdminServicesNewRouteImport } from './routes/admin.services.new'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminServicesIdEditRouteImport } from './routes/admin.services.$id.edit'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'
import { Route as AdminBlogsIdEditRouteImport } from './routes/admin.blogs.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTranslateBlogRoute = ApiTranslateBlogRouteImport.update({
  id: '/api/translate-blog',
  path: '/api/translate-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRoute = ApiTagsRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugTranslationsRoute = ApiDebugTranslationsRouteImport.update({
  id: '/api/debug-translations',
  path: '/api/debug-translations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogsRoute = ApiBlogsRouteImport.update({
  id: '/api/blogs',
  path: '/api/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculatorSettingsRoute = AdminCalculatorSettingsRouteImport.update({
  id: '/calculator-settings',
  path: '/calculator-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculatorQuotesRoute = AdminCalculatorQuotesRouteImport.update({
  id: '/calculator-quotes',
  path: '/calculator-quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBlogsSlugRoute = ApiBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogsRoute,
} as any)
const AdminServicesNewRoute = AdminServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogsRoute,
} as any)
const AdminServicesIdEditRoute = AdminServicesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminBlogsIdEditRoute = AdminBlogsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/calculator-quotes': typeof AdminCalculatorQuotesRoute
  '/admin/calculator-settings': typeof AdminCalculatorSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/debug-translations': typeof ApiDebugTranslationsRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/translate-blog': typeof ApiTranslateBlogRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/calculator-quotes': typeof AdminCalculatorQuotesRoute
  '/admin/calculator-settings': typeof AdminCalculatorSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/debug-translations': typeof ApiDebugTranslationsRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/translate-blog': typeof ApiTranslateBlogRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/calculator-quotes': typeof AdminCalculatorQuotesRoute
  '/admin/calculator-settings': typeof AdminCalculatorSettingsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/blogs': typeof ApiBlogsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/debug-translations': typeof ApiDebugTranslationsRoute
  '/api/tags': typeof ApiTagsRoute
  '/api/translate-blog': typeof ApiTranslateBlogRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/services/new': typeof AdminServicesNewRoute
  '/api/blogs/$slug': typeof ApiBlogsSlugRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/admin/blogs'
    | '/admin/calculator-quotes'
    | '/admin/calculator-settings'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/debug-translations'
    | '/api/tags'
    | '/api/translate-blog'
    | '/admin/'
    | '/admin/blogs/new'
    | '/admin/products/new'
    | '/admin/projects/new'
    | '/admin/services/new'
    | '/api/blogs/$slug'
    | '/admin/blogs/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin/blogs'
    | '/admin/calculator-quotes'
    | '/admin/calculator-settings'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/debug-translations'
    | '/api/tags'
    | '/api/translate-blog'
    | '/admin'
    | '/admin/blogs/new'
    | '/admin/products/new'
    | '/admin/projects/new'
    | '/admin/services/new'
    | '/api/blogs/$slug'
    | '/admin/blogs/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/services/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/admin/blogs'
    | '/admin/calculator-quotes'
    | '/admin/calculator-settings'
    | '/admin/categories'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/users'
    | '/api/blogs'
    | '/api/categories'
    | '/api/contact'
    | '/api/debug-translations'
    | '/api/tags'
    | '/api/translate-blog'
    | '/admin/'
    | '/admin/blogs/new'
    | '/admin/products/new'
    | '/admin/projects/new'
    | '/admin/services/new'
    | '/api/blogs/$slug'
    | '/admin/blogs/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/projects/$id/edit'
    | '/admin/services/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiBlogsRoute: typeof ApiBlogsRouteWithChildren
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiDebugTranslationsRoute: typeof ApiDebugTranslationsRoute
  ApiTagsRoute: typeof ApiTagsRoute
  ApiTranslateBlogRoute: typeof ApiTranslateBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/translate-blog': {
      id: '/api/translate-blog'
      path: '/api/translate-blog'
      fullPath: '/api/translate-blog'
      preLoaderRoute: typeof ApiTranslateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-translations': {
      id: '/api/debug-translations'
      path: '/api/debug-translations'
      fullPath: '/api/debug-translations'
      preLoaderRoute: typeof ApiDebugTranslationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blogs': {
      id: '/api/blogs'
      path: '/api/blogs'
      fullPath: '/api/blogs'
      preLoaderRoute: typeof ApiBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculator-settings': {
      id: '/admin/calculator-settings'
      path: '/calculator-settings'
      fullPath: '/admin/calculator-settings'
      preLoaderRoute: typeof AdminCalculatorSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculator-quotes': {
      id: '/admin/calculator-quotes'
      path: '/calculator-quotes'
      fullPath: '/admin/calculator-quotes'
      preLoaderRoute: typeof AdminCalculatorQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/blogs/$slug': {
      id: '/api/blogs/$slug'
      path: '/$slug'
      fullPath: '/api/blogs/$slug'
      preLoaderRoute: typeof ApiBlogsSlugRouteImport
      parentRoute: typeof ApiBlogsRoute
    }
    '/admin/services/new': {
      id: '/admin/services/new'
      path: '/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminServicesNewRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
    '/admin/services/$id/edit': {
      id: '/admin/services/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/services/$id/edit'
      preLoaderRoute: typeof AdminServicesIdEditRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/blogs/$id/edit': {
      id: '/admin/blogs/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminBlogsIdEditRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
  }
}

interface AdminBlogsRouteChildren {
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIdEditRoute: typeof AdminBlogsIdEditRoute
}

const AdminBlogsRouteChildren: AdminBlogsRouteChildren = {
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIdEditRoute: AdminBlogsIdEditRoute,
}

const AdminBlogsRouteWithChildren = AdminBlogsRoute._addFileChildren(
  AdminBlogsRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesNewRoute: typeof AdminServicesNewRoute
  AdminServicesIdEditRoute: typeof AdminServicesIdEditRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesNewRoute: AdminServicesNewRoute,
  AdminServicesIdEditRoute: AdminServicesIdEditRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRouteWithChildren
  AdminCalculatorQuotesRoute: typeof AdminCalculatorQuotesRoute
  AdminCalculatorSettingsRoute: typeof AdminCalculatorSettingsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRouteWithChildren,
  AdminCalculatorQuotesRoute: AdminCalculatorQuotesRoute,
  AdminCalculatorSettingsRoute: AdminCalculatorSettingsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiBlogsRouteChildren {
  ApiBlogsSlugRoute: typeof ApiBlogsSlugRoute
}

const ApiBlogsRouteChildren: ApiBlogsRouteChildren = {
  ApiBlogsSlugRoute: ApiBlogsSlugRoute,
}

const ApiBlogsRouteWithChildren = ApiBlogsRoute._addFileChildren(
  ApiBlogsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiBlogsRoute: ApiBlogsRouteWithChildren,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiContactRoute: ApiContactRoute,
  ApiDebugTranslationsRoute: ApiDebugTranslationsRoute,
  ApiTagsRoute: ApiTagsRoute,
  ApiTranslateBlogRoute: ApiTranslateBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
